services:
  api:
    build: ./images/api
    ports:
      - 8080:3000
    environment: 
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "start"]

  db:
    ports:
      - 5432:5432
    image: postgres:16.0
    environment: 
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
      POSTGRES_HOST_AUTH_METHOD: 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 10
  